//------------------------------------------------------------------------------
// <auto-generated>
//     ??ì½”ë“œ???œí”Œë¦¿ì—???ì„±?˜ì—ˆ?µë‹ˆ??
//
//     ???Œì¼???˜ë™?¼ë¡œ ë³€ê²½í•˜ë©??‘ìš© ?„ë¡œê·¸ë¨?ì„œ ?ˆê¸°ì¹??Šì? ?™ì‘??ë°œìƒ?????ˆìŠµ?ˆë‹¤.
//     ???Œì¼???˜ë™?¼ë¡œ ë³€ê²½í•˜ë©?ì½”ë“œê°€ ?¤ì‹œ ?ì„±????ë³€ê²??´ìš©????–´?ë‹ˆ??
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfNaverMovieFinder.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFavoriteMovies
    {
        public int Idx { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }
        public string Image { get; set; }
        public string SubTitle { get; set; }
        public string PubDate { get; set; }
        public string Director { get; set; }
        public string Actor { get; set; }
        public string UserRating { get; set; }
        public System.DateTime RegDate { get; set; }
    }
}
