//------------------------------------------------------------------------------
// <auto-generated>
//     ??ì½”ë“œ???œí”Œë¦¿ì—???ì„±?˜ì—ˆ?µë‹ˆ??
//
//     ???Œì¼???˜ë™?¼ë¡œ ë³€ê²½í•˜ë©??‘ìš© ?„ë¡œê·¸ë¨?ì„œ ?ˆê¸°ì¹??Šì? ?™ì‘??ë°œìƒ?????ˆìŠµ?ˆë‹¤.
//     ???Œì¼???˜ë™?¼ë¡œ ë³€ê²½í•˜ë©?ì½”ë“œê°€ ?¤ì‹œ ?ì„±????ë³€ê²??´ìš©????–´?ë‹ˆ??
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfSMSApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Store()
        {
            this.Reader = new HashSet<Reader>();
            this.Stock = new HashSet<Stock>();
        }
    
        public int StoreID { get; set; }
        public string StoreName { get; set; }
        public string StoreLocation { get; set; }
        public bool ItemStatus { get; set; }
        public int TagID { get; set; }
        public int BarcodeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reader> Reader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stock { get; set; }
    }
}
